version: "3.7"
services:
  api:
    container_name: dev-chat-api
    build: .
    ports:
      - 8000:8000

  dynamo-db:
    container_name: dev-chat-dynamodb
    image: amazon/dynamodb-local:1.16.0
    # To persist data - https://stackoverflow.com/a/52853294/7127317
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data
    ports:
      - 8001:8000

volumes:
  dynamodb_data:
