name: API CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install
        run: npm ci
        working-directory: ./api
      - name: Format
        run: npm run check-format
        working-directory: ./api
      - name: Lint
        run: npm run lint
        working-directory: ./api
      - name: Test
        run: npm test
        working-directory: ./api
      - name: Build
        run: npm run build
        working-directory: ./api
